## importing necessary libraries

In [49]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder,MinMaxScaler

## data loading


In [79]:
data=pd.read_csv("kerala.csv")
data.drop("SUBDIVISION",axis=1,inplace=True)
x_input=data.drop("FLOODS",axis=1)
x_input = x_input.drop("YEAR",axis = 1)
y_output=data["FLOODS"]
year = data["YEAR"]

print(x_input)


      JAN   FEB   MAR    APR    MAY     JUN     JUL     AUG    SEP    OCT  \
0    28.7  44.7  51.6  160.0  174.7   824.6   743.0   357.5  197.7  266.9   
1     6.7   2.6  57.3   83.9  134.5   390.9  1205.0   315.8  491.6  358.4   
2     3.2  18.6   3.1   83.6  249.7   558.6  1022.5   420.2  341.8  354.1   
3    23.7   3.0  32.2   71.5  235.7  1098.2   725.5   351.8  222.7  328.1   
4     1.2  22.3   9.4  105.9  263.3   850.2   520.5   293.6  217.2  383.5   
..    ...   ...   ...    ...    ...     ...     ...     ...    ...    ...   
113   4.6  10.3  17.9   95.7  251.0   454.4   677.8   733.9  298.8  355.5   
114   3.1   5.8  50.1  214.1  201.8   563.6   406.0   252.2  292.9  308.1   
115   2.4   3.8  35.9  143.0  186.4   522.2   412.3   325.5  173.2  225.9   
116   1.9   6.8   8.9   43.6  173.5   498.5   319.6   531.8  209.5  192.4   
117  29.1  52.1  48.6  116.4  183.8   625.4  1048.5  1398.9  423.6  356.1   

       NOV    DEC   ANNUAL RAINFALL  
0    350.8   48.4            3248.6  

In [48]:
ldr=LabelEncoder()
y_output=ldr.fit_transform(y_output)

x_input=MinMaxScaler().fit_transform(x_input)
x_input = pd.DataFrame(x_input)
x_input = pd.concat([year,x_input],axis=1)
x_input.rename(columns={"YEAR":13},inplace=True)

print(x_input)


# x_input.to_csv("created_data.csv",index=False)   


       13        0         1         2         3         4         5   \
0    1901  0.000000  0.000000  0.343713  0.565823  0.237218  0.653179   
1    1902  0.008547  0.008547  0.080240  0.032911  0.263473  0.314807   
2    1903  0.017094  0.017094  0.038323  0.235443  0.013819  0.313473   
3    1904  0.025641  0.025641  0.283832  0.037975  0.147858  0.259671   
4    1905  0.034188  0.034188  0.014371  0.282278  0.042837  0.412628   
..    ...       ...       ...       ...       ...       ...       ...   
113  2014  0.965812  0.965812  0.055090  0.130380  0.081990  0.367274   
114  2015  0.974359  0.974359  0.037126  0.073418  0.230309  0.893731   
115  2016  0.982906  0.982906  0.028743  0.048101  0.164901  0.577590   
116  2017  0.991453  0.991453  0.022754  0.086076  0.040534  0.135616   
117  2018  1.000000  1.000000  0.348503  0.659494  0.223399  0.459315   

           6         7         8         9         10        11        12  \
0    0.176977  0.696472  0.423473  0.146603  0

### the input data is now transfered into created_data.csv

In [60]:
fetched_data = np.loadtxt("created_data.csv",delimiter=",")   # this is the input_data and y_output is the output data


# print(y_output[:10])

# print(fetched_data)
# print(y_output)


### Splitting train and test data

In [83]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(fetched_data,y_output,test_size=0.08)

print(x_train)


[[1.93600000e+03 2.99145299e-01 1.43712575e-02 ... 5.37563604e-01
  9.14935707e-02 4.05332335e-01]
 [1.95000000e+03 4.18803419e-01 1.19760479e-03 ... 3.52289734e-01
  4.30267062e-02 4.48298810e-01]
 [1.91300000e+03 1.02564103e-01 3.71257485e-02 ... 2.34660281e-01
  2.26013848e-01 2.25438815e-01]
 ...
 [1.90800000e+03 5.98290598e-02 9.58083832e-02 ... 4.90870997e-02
  5.39070227e-02 2.41036519e-01]
 [1.92400000e+03 1.96581197e-01 2.31137725e-01 ... 3.93295421e-01
  2.48763600e-01 8.97429498e-01]
 [1.97300000e+03 6.15384615e-01 0.00000000e+00 ... 1.58635139e-01
  2.65578635e-01 1.42958157e-01]]


# Model selection

In [64]:
from sklearn.tree import DecisionTreeClassifier

model = DecisionTreeClassifier()

model.fit(x_train,y_train)

DecisionTreeClassifier()

### Testing

In [65]:
prediction = model.predict(x_test)
print(prediction)

print(y_test)

[0 0 1 0 0 1 0 1 1 0]
[0 0 1 0 0 1 0 1 1 0]


## Accuracy score 

In [66]:
from sklearn.metrics import accuracy_score

score = accuracy_score(prediction,y_test)

print("accuracy score is", score)

accuracy score is 1.0


## Checking flood chance


In [69]:
year = int(input("Enter the year : "))
print("Enter recorded rainfall of each month! \n")

jan = float(input("January :"))
feb = float(input("february :"))
mar = float(input("march :"))
apr = float(input("april :"))
may = float(input("may :"))
jun = float(input("june :"))
jul = float(input("july :"))
aug = float(input("augest :"))
sep = float(input("september :"))
oct = float(input("october :"))
nov = float(input("november :"))
dec = float(input("december :"))

monthly_data = [jan,feb,mar,apr,may,jun,jul,aug,sep,oct,nov,dec]

# 2.4,0.9,0.1,43,218.4,819.3,767.8,508,297.5,290.7,287.6,3.7,3239.5

Enter recorded rainfall of each month! 



In [88]:
annual_fall = sum(monthly_data)
array_input = np.array(monthly_data+[annual_fall]).reshape(1,13)
scaled_input = MinMaxScaler().fit_transform(array_input)
final_input = scaled_input
print(scaled_input)

# print()

# input_list = MinMaxScaler().fit_transform(x_input)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
